apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: service2-container
        image: swoodhouse5194/service2:latest
        env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: user
              key: password
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: pw
              key: password
        - name: RABBITMQ_SVC_NAME
          value: "rabbitmq-demo"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
      - name: service3-container
        image: swoodhouse5194/service3:latest
        env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: user
              key: password
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: pw
              key: password
        - name: RABBITMQ_SVC_NAME
          value: "rabbitmq-demo"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
      - name: service4-container
        image: swoodhouse5194/service4:latest
        env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: user
              key: password
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: pw
              key: password
        - name: RABBITMQ_SVC_NAME
          value: "rabbitmq-demo"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
      - name: service5-container
        image: swoodhouse5194/service5:latest
        env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: user
              key: password
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: pw
              key: password
        - name: RABBITMQ_SVC_NAME
          value: "rabbitmq-demo"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
      - name: service6-container
        image: swoodhouse5194/service6:latest
        env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: user
              key: password
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: pw
              key: password
        - name: RABBITMQ_SVC_NAME
          value: "rabbitmq-demo"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi